name: shibli_shorts
description: A demo Flutter shorts app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.7.0
  cloud_firestore: ^5.0.3
  firebase_storage: ^11.0.14
  video_player: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
